### ISSUE TITLE
macos compile nit.

### ISSUE THREAD

**Issue by icepic** [libcg/bfp#13]
gcc (actually clang) didn't like c++ options,
$ make
g++ -o lib/posit.o -std=c++11 -Ilib -Itest -O2 -Wall -g -c lib/posit.cpp
gcc -o lib/pack.o -std=c++11 -Ilib -Itest -O2 -Wall -g -c lib/pack.c
error: invalid argument '-std=c++11' not allowed with 'C/ObjC'

diff --git a/Makefile b/Makefile
index d9514a3..0a30df8 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
 CC = gcc
 CXX = g++
-CFLAGS = -std=c++11 -Ilib -Itest -O2 -Wall -g
-CXXFLAGS = $(CFLAGS)
+CFLAGS = -Ilib -Itest -O2 -Wall -g
+CXXFLAGS = $(CFLAGS) -std=c++11
 
 LIB_TARGET = lib/libbfp.a

**Comment by libcg** [comment]
Should be fixed by e3b8c04. Feel free to reopen if needed. Thanks!
