### ISSUE TITLE
Is there a way yet to convert ints and floats to Posits?

### ISSUE THREAD

**Issue by akkartik** [libcg/bfp#14]
I would like to use Posits in a language I'm working on. But I'm stumped at the simplest hurdle: initializing a variable.

**Comment by akkartik** [comment]
Never mind, I [found it](https://github.com/libcg/bfp/blob/36f94d3c24/lib/pack.h#L22) right after I posted.

**Comment by libcg** [comment]
You can use `Posit::getFloat` and `Posit::getDouble`.

**Comment by libcg** [comment]
Or `Posit::set()` :)
