### ISSUE TITLE
Reciprocal is very wrong

### ISSUE THREAD

**Issue by leobru** [libcg/bfp#9]
auto three = Posit(32, 1);
    three.set(3.0);
    auto one_third = three.rec();
    three.print();
    one_third.print();

Prints

    {32, 1} 01011000000000000000000000000000 (0) -> +10 1 1000000000000000000000000000 = 3
    {32, 1} 00101000000000000000000000000000 (-1) -> +01 0 1000000000000000000000000000 = 0.375

OH MY GOD!

Where does the idea come from that computing reciprocals don't require changing the fraction part?

**Comment by libcg** [comment]
Thanks for trying this out. I doubt the reciprocal itself is wrong as the operation is very simple and well defined however, the double -> posit (when setting value) and posit -> double (when printing) conversion are probably doing something wrong.

You should also note that rounding is not implemented yet. Both conversions might be losing precision.

**Comment by libcg** [comment]
Hmm... Looking at the values and calculating by hand it seems you are right. Conversions are correct and the reciprocal itself is broken. That's very odd.

**Comment by libcg** [comment]
Uh oh. You're right, it isn't as simple when fraction bits are involved. So rec() is broken for nbits >= 5 right now. My fault for grossly extrapolating from Unum slides.

**Comment by leobru** [comment]
When computing a reciprocal of X, you're guaranteed that the fraction of the result will be of the same length, say, N. Therefore you can divide integer 2^(2N) by X, and take N significant bits of the quotient, rounding according to the remaining bits of the quotient.
Also note that doing the division operation directly results in greater accuracy than computing a reciprocal and multiplying, unless the reciprocal is exact.

**Comment by libcg** [comment]
Fixed by 16ffa9285. Thanks for the report!
